CONFIG_NAME: "easy_vqa"

DATASET_NAME: "easy_vqa"
DATA_DIR: "/home/nino/Documents/Datasets/ExtEasyVQA/"
N_WORKERS: 12
IM_SIZE: 128

MODEL:
  CNN_TYPE: "resnet18"
  EF_TYPE: "sbert_reduced"
  ATTENTION: True
  N_HIDDEN: 256
  TYPE: "all"

TRAIN:
  BATCH_SIZE: 24 #default 24
  MAX_EPOCH: 30
  LR: 0.002
  CHECKPOINT: ""
