CONFIG_NAME: "flowers"

DATASET_NAME: "flowers"

TREE:
  BRANCH_NUM: 2

TRAIN:
  N_SAMPLES: 3670
  N_CLASSES: 5
  BATCH_SIZE: 24
  MAX_EPOCH: 600
  DISCRIMINATOR_LR: 0.0002
  GENERATOR_LR: 0.0002
  COEFF:
    UNCOND_LOSS: 1.0

GAN:
  EMBEDDING_DIM: 10
  DF_DIM: 64
  GF_DIM: 32
  Z_DIM: 100

TEXT:
  DIMENSION: 5
